name: No idea
on: [push]
jobs:
  Do-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Asdf
        run: echo "${{ github.workspace }}/lorem/ipsum"
        run:  mkdir -p "${{ github.workspace }}/lorem/ipsum"
        run:  ls "${{ github.workspace }}"